name: Firebase Hosting Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - run: |
         flutter config --enable-web
         flutter upgrade
         flutter pub get
         flutter test --platform chrome
         flutter build web --release
      
      - run: cp -R build/web/* public/
      
      - uses: w9jds/firebase-action@master 
      
        with:
          args: deploy --only hosting
        
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
