name: Firebase Hosting Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      
      - run: cp -R build/web/* public/
      
      - uses: w9jds/firebase-action@master --project <flutter---web>
      
        with:
          args: deploy --only hosting
        
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
